routes/web.php
<?php
use Illuminate\Support\Facades\View;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::resource('', 'DashboardController');

Route::get('agenda/consulta', 'ScheduleController@agendaConsultaEsp');
Route::get('agenda/consulta/{id}/profissional', 'ScheduleController@agendaConsultaProf');
Route::get('agenda/consulta/{id}/profissional/{idEmployee}/data', 'ScheduleController@agendaConsultaData');

Route::get('agenda/procedimento', 'ScheduleController@agendaProcedimentoProc');
Route::get('agenda/procedimento/{id}/profissional', 'ScheduleController@agendaProcedimentoProf');

Route::get('agenda/{id}', 'ScheduleController@getSchedule');
Route::resource('agenda', 'ScheduleController');

Route::resource('dashboard', 'DashboardController');
Route::resource('clinica', 'ClinicController');
Route::resource('especialidades', 'SpecialityController');
Route::resource('convenios', 'AgreementController');
Route::resource('funcionarios', 'EmployeeController');

Route::get('historico', 'PacientController@history')->name('pacientes.history');
Route::resource('pacientes', 'PacientController');

Route::resource('planos', 'PlanController');
Route::resource('categorias', 'CategoriesController');
Route::resource('despesas', 'Bills_paymentController');
Route::resource('receitas', 'Bills_receiptController');
Route::resource('procedimentos', 'ClinicalProcedureController');

Route::get('atendimentos/{id}', 'CallController@index')->name('atendimentos.index');
Route::post('atendimentos', 'CallController@store')->name("atendimentos.store");
// Route::resource('atendimentos', 'CallController');

//Route::resource('relatorios', 'ReportController');

Route::get('/ajuda', function() {
  $user = Auth::user();
  View::share('user', $user);
  return view('help');
});

$this->get('/relatorios', 'ReportController@index');
$this->get('/relatorios/reportCallsMonth', 'ReportController@reportCallsMonth');
$this->get('/relatorios/reportPacients', 'ReportController@reportPacients');
$this->get('/relatorios/reportAgreements', 'ReportController@reportAgreements');
$this->get('/relatorios/reportPlans', 'ReportController@reportPlans');
$this->get('/relatorios/reportEmployees', 'ReportController@reportEmployees');
$this->get('/relatorios/reportBillsReceiptsCategories', 'ReportController@reportBillsReceiptsCategories');
$this->get('/relatorios/reportCallsMonthAgreement', 'ReportController@reportCallsMonthAgreement');
$this->get('/relatorios/reportCallsMonthEmployee', 'ReportController@reportCallsMonthEmployee');
$this->get('/relatorios/reportCallsMonthPacient', 'ReportController@reportCallsMonthPacient');
$this->get('/relatorios/reportBillsPaymentsCategories', 'ReportController@reportBillsPaymentsCategories');


$this->get('/documentos', 'DocumentController@index');
$this->get('/documentos/documentHemograma', 'DocumentController@documentHemograma');
$this->get('/documentos/documentUrianalise', 'DocumentController@documentUrianalise');
$this->get('/documentos/documentAtestado', 'DocumentController@documentAtestado');

//Route::get('pacientes2', function () {
  //  return view('paciente_perfil');
//});

//Route::get('planos2', function () {
  //  return view('planos_form');
//});

resources/views/calls_form.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Agenda</a>
        </li>
        <li class="breadcrumb-item active">
            @if ($action == 1)
                Iniciar Atendimento
            @else
                Editar Atendimento
            @endif
        </li>
      </ol>

        @if ($action == 1)
            <form class="form-horizontal" action="{{ route('atendimentos.store') }}" method="POST">
        @else
            <form class="form" action="{{ route('atendimentos.update', $reg->id) }}" method="post">
            {!! method_field('put') !!}
        @endif
      
        {{ csrf_field() }}

        <input type="hidden" name="id" id="id" value="{{ $id }}"/>
        <input type="hidden" name="discount" id="discount" value="{{ $discount }}"/>

        <div class="form-group">
            <label class="control-label col-sm-4" for="id_employees">Profissional:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="employee" name="employee" value="{{ $employee_name }}" readonly>
                <input type="number" name="id_employees" id="id_employees" value="{{ $schedule->id_employees }}" hidden/>
            </div>   
        </div>  

        <div class="form-group">
            <label class="control-label col-sm-4" for="specialty">Especialidade:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="specialty" name="specialty" value="{{ $speciality_name }}" readonly>
            </div>   
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="pacient">Paciente:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="pacient" name="pacient" value="{{ $schedule->pacient }}" readonly>
                <input type="number" name="id_pacients" id="id_pacients" value="{{ $schedule->id_pacients }}" hidden/>
            </div>   
        </div> 

        
        <div class="form-group">
            <label class="control-label col-sm-4" for="date">Data da Consulta:</label>
            <div class="col-md-5">
                <input type="date" class="form-control" id="date" name="date" placeholder="Data" value="{{ $schedule->date }}" readonly>
            </div>   
        </div>  

        <div class="form-group">
            <label class="control-label col-sm-4" for="hour">Hora da Consulta:</label>
            <div class="col-md-5">
                <input type="time" class="form-control" id="hour" name="hour" placeholder="Hora" value="{{ $schedule->hour }}" readonly>
            </div>   
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-4" for="anamnesis">Anamnesis:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="anamnesis" name="anamnesis" placeholder="Anamnesis" value="{{ $reg->anamnesis or old('anamnesis') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="height">Altura:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="height" name="height" placeholder="Altura" value="{{ $reg->height or old('height') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="weight">Peso:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="weight" name="weight" placeholder="Peso" value="{{ $reg->weight or old('weight') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="pressure">Pressão:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="pressure" name="pressure" placeholder="Pressão" value="{{ $reg->pressure or old('pressure') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="temperature">Temperatura:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="temperature" name="temperature" placeholder="Temperatura" value="{{ $reg->temperature or old('temperature') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="diagnosticHypothesis">Diagnóstico Hipotético:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="diagnosticHypothesis" name="diagnosticHypothesis" placeholder="Diagnóstico Hipotético" value="{{ $reg->diagnosticHypothesis or old('diagnosticHypothesis') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="prescriptionMedication">Prescrição de Medicamentos:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="prescriptionMedication" name="prescriptionMedication" placeholder="Prescrição de Medicamentos" value="{{ $reg->prescriptionMedication or old('prescriptionMedication') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="prescriptionExam">Prescrição de Exames:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="prescriptionExam" name="prescriptionExam" placeholder="Prescrição de Exames" value="{{ $reg->prescriptionExam or old('prescriptionExam') }}">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-4" for="note">Observações:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="note" name="note" placeholder="Observações" value="{{ $reg->note or old('note') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="id_clinical_procedures">Procedimento Clínico Realizado:</label>
            <div class="col-md-5">
                <select class="form-control" id="id_clinical_procedures" name="id_clinical_procedures">
                    <option value="0">Selecione</option>
                    @foreach ($procedures as $p)
                        <option
                            value="{{ $p->id }}" @if ((isset ($precedures) and $p->id == $p->id_clinical_procedures) or old('id_clinical_procedures') == $p->id) selected @endif
                            data-value="{{ $p->value }}">{{ $p->title }}</option>
                    @endforeach
                </select>
            </div>          
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-4" for="valueClinicalProcedure">Valor do Procedimento Clínico:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="valueClinicalProcedure" name="valueClinicalProcedure" value="{{ $reg->valueClinicalProcedure or old('valueClinicalProcedure') }}" readonly>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="valueConsultation">Valor da Consulta:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="valueConsultation" name="valueConsultation" value="120.00" readonly>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="total_value">Valor total:</label>
            <div class="col-md-5">
                <input type="text" class="form-control" id="total_value" name="total_value" value="120.00" readonly>
            </div>
        </div>


        <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Encerrar Atendimento</button>
            </div>
        </div>
    </form>



    <form style="display: inline-block;" method="POST" action="{{ route('agenda.destroy', $schedule->id ) }}">
        {{ method_field('DELETE') }}
        {{ csrf_field() }}
        <button type="submit" class="btn btn-danger">Excluir</button>
    </form>
    
    {{-- <script>
        window.onload = function() {
            const procedures = document.querySelector('#id_clinical_procedures');
            const procedureValueEl = document.querySelector('#valueClinicalProcedure');
            const totalValueEl = document.querySelector('#total_value');

            procedures.addEventListener('change', ev => {
                const target = ev.target;
                const option = ev.target.options[ev.target.selectedIndex];
                const value = parseFloat(option.getAttribute('data-value'));

                procedureValueEl.value = value.toFixed(2);
                totalValueEl.value = (value + 120).toFixed(2);
            });
        }
    </script> --}}
@endsection

resources/views/categories_form.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Clínica</a>
        </li>
        <li class="breadcrumb-item">
          <a href="index.html">Categorias</a>
        </li>
        <li class="breadcrumb-item active">
            @if ($action == 1)
                Nova categoria
            @else
                Editar categoria
            @endif
        </li>
      </ol>

        @if ($action == 1)
            <form class="form-horizontal" action="{{ route('categorias.store') }}" method="POST">
        @else
            <form class="form" action="{{ route('categorias.update', $reg->id) }}" method="post">
            {!! method_field('put') !!}
        @endif
      
        {{ csrf_field() }}

        <div class="form-group">
            <label class="control-label col-sm-4" for="name">Nome:</label>
            <div class="col-md-5">
                <input type="name" class="form-control" id="name" name="name" placeholder="Nome da categoria" value="{{ $reg->name or old('name') }}">
            </div>
        </div>

        <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Salvar</button>
            </div>
        </div>
    </form>

@endsection

resources/views/clinic.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ route('clinica.index') }}">Clínica</a>
        </li>
        <li class="breadcrumb-item active">Dados Gerais</li>
      </ol>
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-building"></i> Clínica
        </div>
        
        @if (isset($clinics->id))
          <a href="/clinica/{{$clinics->id}}/edit" class="btn btn-success">Editar</a>
        @else
          <a href="/clinica/create" class="btn btn-success">Nova Clínica</a>
        @endif

      <div class="row clinic-container">
        <div class="col-12">
          @if (isset($clinics->id))
            <h2>{{ $clinics->fantasyName }}</h2>
            <hr>
            <h5>Razão Social:</h5>
            <p>{{ $clinics->socialName }}</p>
            <h5>CNPJ:</h5>
            <p>{{ $clinics->cnpj }}</p>
            <h5>Telefone:</h5>
            <p>{{ $users->homePhone }} / {{ $users->cellPhone }}</p>
            <h5>E-mail:</h5>
            <p>{{ $users->email }}</p>
            <h5>Endereço:</h5>
            <p>{{ $users->address }} - {{ $users->city }} - {{ $users->cep }}</p>
            <h5>Dados Financeiros:</h5>
            <p>{{ $clinics->bank }} / {{ $clinics->agency }}-{{ $clinics->bankAccount }}</p>
          @else
            <p>Não há clínica cadastrada!</p>
          @endif
        </div>
      </div>

@endsection

resources/views/clinicalProcedure.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Clínica</a>
        </li>
        <li class="breadcrumb-item active">Procedimentos Clínicos</li>
      </ol>
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-building"></i> Procedimentos Clínicos
        </div>
        <a href="{{ route('procedimentos.create') }}" class="btn btn-success">Novo Procedimento Clínico</a>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Título</th>
                  <th>Valor (R$)</th>
                  <th>Observações</th>
                  <th style="width: 80px">Ações</th>
                </tr>
              </thead>

                @foreach ($procedures as $p)
                  <tr>
                    <td>{{ $p->title }}</td>
                    <td>R$ {{ number_format($p->value, 2, ',', '.') }}</td>

                    <td>{{ $p->note }}</td>
                    <td style="text-align: center; width: 80px">
                      <a href="/procedimentos/{{ $p->id }}/edit">
                        <i class="fa fa-edit"></i>
                      </a>
  
                      <form style="display: inline-block;" method="POST" action="{{ route('procedimentos.destroy', $p->id) }}">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
  
                        <button type="submit" class="custom-btn">
                          <i class="fa fa-trash"></i>
                        </button>
                      </form>
                    </td>
                  </tr>
                @endforeach   
              </tbody>
            </table>
            
          </div>
        </div>
      </div>

@endsection

resources/views/documentAtestado.blade.php
<img src="images/logo-healer.png" class="img-rounded">

<h5>Atestado</h5>

<p>Atesto para os devidos fins que ________________________________ necessita de repousto e afastamento de suas atividades profissionais durante _______ dias a partir da data de hoje. CID da doença _______.</p>

resources/views/patients.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Pacientes</a>
        </li>
      </ol>

      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-circle"></i> Pacientes
        </div>
        <a href="{{ route('pacientes.create') }}" class="btn btn-success">Novo Paciente</a>

        @foreach ( $pacients as $p )
          <a class="list-group-item list-group-item-action" href="/pacientes/{{$p->id}}/edit">
            <div class="media">
              <img class="d-flex mr-3 rounded-circle" src="/images/logo-square.png" alt="">
              <div class="media-body">
                <strong>{{ $p->name }}</strong>
                <div class="text-muted smaller">{{ $p->city }} - {{ $p->cellPhone }}</div>
              </div>
            </div>
          </a>
        @endforeach

          </div>
        </div>
      </div>

@endsection      

resources/views/patients_form.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ route('pacientes.index') }}">Paciente</a>
        </li>
        <li class="breadcrumb-item active">
            @if ($action == 1)
                Novo Paciente
            @else
                Editar Paciente
            @endif
        </li>
    </ol>

    @if ($action == 1)
        <form class="form-horizontal" action="{{ route('pacientes.store') }}" method="POST">
        
    @else
        <form class="form" action="{{ route('pacientes.update', $reg->id) }}" method="post">
        {!! method_field('put') !!}
        <input type="hidden" name="id_users" value="{{ $reg->id_users }}"/>
    @endif
      
        {{ csrf_field() }}

        <div class="card mb-3 custom-items">
            <div class="list-group list-group-flush small">
                <div class="list-group-item list-item-center">
                    {{-- <img class="d-flex rounded-circle" src="https://images.unsplash.com/photo-1513732822839-24f03a92f633?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c019fe313afd6ef860d09b17e8066559&auto=format&fit=crop&w=1534&q=80" alt=""> --}}

                <img class="rounded-circle list-group-item list-item-center"  style="width: 64px; padding: 0; height: 64px; margin-top: 20px;" src="/images/logo-square.png" alt="">
                </div>
                <div class="grid-50 --vertical-space">
                    <div class="line ">
                        <div class="media-body">
                            <h5>Nome Completo:</h5>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Nome Completo" value="{{ $reg->name or old('name') }}" required>
                        </div>
                    </div>
                    <div class="line ">
                        <div >
                            <h5>E-mail:</h5>
                                <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{ $reg->email or old('email') }}" required>
                            </div>    
                        <div >    
                            <h5>Data de Nascimento:</h5>
                            <input type="date" class="form-control" id="birthDate" name="birthDate" placeholder="Data de Nascimento" value="{{ $reg->birthDate or old('birthDate') }}" required>
                        </div>
                        <div >
                            <h5>Senha:</h5>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Senha" value="{{ $reg->password or old('password') }}" required>
                        </div> 
                    </div>
                    <div class="line">     
                        <div >
                            <h5>Tel. Celular:</h5>
                            <input type="tel" class="form-control" id="cellPhone" name="cellPhone" placeholder="Telefone" value="{{ $reg->cellPhone or old('cellPhone') }}" required>
                        </div>
                        <div >
                            <h5>Tel. Residencial:</h5>
                            <input type="tel" class="form-control" id="homePhone" name="homePhone" placeholder="Telefone" value="{{ $reg->homePhone or old('homePhone') }}" required>
                            </div>  
                        <div >   
                            <h5>CPF:</h5>
                            <input type="tel" class="form-control" id="cpf" name="cpf" placeholder="CPF" value="{{ $reg->cpf or old('cpf') }}" required>
                        </div>
                    </div>  
                    <div class="line">     
                            <div >
                                <h5>Endereço:</h5>
                                <input type="text" class="form-control" id="address" name="address" placeholder="Endereço" value="{{ $reg->address or old('address') }}" required>
                            </div>
                            <div >
                                <h5>Cidade:</h5>
                                <input type="text" class="form-control" id="city" name="city" placeholder="Cidade" value="{{ $reg->city or old('city') }}" required>
                                </div>  
                            <div >   
                                <h5>CEP:</h5>
                                <input type="tel" class="form-control" id="cep" name="cep" placeholder="CEP" value="{{ $reg->cep or old('cep') }}" required>
                            </div>
                        </div>   
                    <div class="line ">
                            <div >
                                <h5>Convênio:</h5> 
                                    <select class="form-control" id="id_agreements" name="id_agreements">
                                        <option value="0">Selecione</option>
                                        @foreach ($agreements as $a)
                                            <option value="{{ $a->id }}" @if ((isset ($reg) and $a->id == $reg->id_agreements) or old('id_agreements') == $a->id) selected @endif>{{ $a->name }}</option>
                                        @endforeach
                                    </select>     
                            </div>    
                            <div >    
                                <h5>Plano:</h5>
                                <select class="form-control" id="id_plans" name="id_plans">
                                    <option value="0">Selecione</option>
                                        @foreach ($plans as $p)
                                        <option value="{{ $p->id }}" @if ((isset ($reg) and $p->id == $reg->id_plans) or old('id_plans') == $p->id) selected @endif>{{ $p->name }}</option>
                                        @endforeach
                                </select>   
                            </div>
                            <div >    
                                <h5>RG:</h5>
                                <input type="number" class="form-control" id="rg" name="rg" placeholder="RG" value="{{ $reg->rg or old('rg') }}" required>    
                            </div> 
                    </div>  
                </div>
            </div>
        </div>
        
        <button type="submit" class="btn btn-default">Salvar</button>
    </form>

    @if ($action == 2)
        <form style="display: inline-block;" method="POST" action="{{ route('pacientes.destroy', $reg->id) }}">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <input type="hidden" name="id_users" value="{{ $reg->id_users }}"/>

            <button type="submit" class="btn btn-danger">Excluir</button>
        </form>
    @endif

@endsection
@section('extra_scripts')
    <script>
        
    </script>
@endsection

resources/views/sidebar.blade.php
<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    @if ($user->type != 3)
    <!-- Menu Dashboard-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <a class="nav-link" href="{{ route('dashboard.index') }}">
        <i class="fa fa-fw fa-dashboard"></i>
        <span class="nav-link-text">Dashboard</span>
        </a>
    </li>
    @endif

    @if ($user->type == 1)
    <!-- Menu Clínica-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Clínica">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#dropClinica" data-parent="#exampleAccordion">
        <i class="fa fa-fw fa-building"></i>
        <span class="nav-link-text">Clínica</span>
        </a>
        <ul class="sidenav-second-level collapse" id="dropClinica">
        <li>
            <a href="{{ route('clinica.index') }}">Dados Gerais</a>
        </li>
        <li>
            <a href="{{ route('especialidades.index') }}">Especialidades</a>
        </li>
        <li>
            <a href="{{ route('convenios.index') }}">Convênios</a>
        </li>
        <li>
            <a href="{{ route('planos.index') }}">Planos</a>
        </li>
        <li>
            <a href="{{ route('funcionarios.index') }}">Funcionários</a>
        </li>
        <li>
            <a href="{{ route('procedimentos.index') }}">Procedimentos Clínicos</a>
        </li>
        <li>
            <a href="/documentos">Modelo de Documentos</a>
        </li>
        </ul>
    </li>
    @endif

    @if ($user->type != 3)
    <!-- Menu Paciente-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Paciente">
        <a class="nav-link" href="{{ route('pacientes.index') }}">
        <i class="fa fa-fw fa-users"></i>
        <span class="nav-link-text">Paciente</span>
        </a>
    </li>
    @endif

    @if ($user->type == 1)
    <!-- Menu Financeiro-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Financeiro">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#dropFinanceiro" data-parent="#exampleAccordion">
        <i class="fa fa-fw fa-money"></i>
        <span class="nav-link-text">Financeiro</span>
        </a>
        <ul class="sidenav-second-level collapse" id="dropFinanceiro">
        <li>
            <a href="{{ route('categorias.index') }}">Categorias</a>
        </li>
        <li>
            <a href="{{ route('despesas.index') }}">Contas a Pagar</a>
        </li>
        <li>
            <a href="{{ route('receitas.index') }}">Contas a Receber</a>
        </li>
        </ul>
    </li>
    @endif

    @if ($user->type != 3)
    <!-- Menu Agenda-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Agenda">
        <a class="nav-link" href="{{ route('agenda.index') }}">
        <i class="fa fa-fw fa-calendar"></i>
        <span class="nav-link-text">Agenda</span>
        </a>
    </li>
    @endif

    @if ($user->type == 1)
    <!-- Menu Relatório-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Relatorio">
        <a class="nav-link" href="/relatorios">
        <i class="fa fa-fw fa-clipboard"></i>
        <span class="nav-link-text">Relatório</span>
        </a>
    </li>
    @endif

    @if ($user->type == 3)
        <!-- Menu Histórico-->
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Histórico">
            <a class="nav-link" href="/historico">
            <i class="fa fa-fw fa-book"></i>
            <span class="nav-link-text">Histórico</span>
            </a>
        </li>
    @endif    

    @if ($user->type != 3)
    <!-- Menu Ajuda-->
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ajuda">
        <a class="nav-link" href="/ajuda">
        <i class="fa fa-fw fa-book"></i>
        <span class="nav-link-text">Ajuda</span>
        </a>
    </li>
    @endif

</ul>

resources/views/specialities_form.blade.php
@extends('base')

@section('container')

<!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Clínica</a>
        </li>
        <li class="breadcrumb-item">
          <a href="index.html">Especialidades</a>
        </li>
        <li class="breadcrumb-item active">
            @if ($action == 1)
                Nova especialidade
            @else
                Editar especialidade
            @endif
        </li>
      </ol>

        @if ($action == 1)
            <form class="form-horizontal" action="{{ route('especialidades.store') }}" method="POST">
        @else
            <form class="form" action="{{ route('especialidades.update', $reg->id) }}" method="post">
            {!! method_field('put') !!}
        @endif
      
        {{ csrf_field() }}

        <div class="form-group">
            <label class="control-label col-sm-4" for="name">Nome:</label>
            <div class="col-md-5">
                <input type="name" class="form-control" id="name" name="name" placeholder="Nome da especialidade" value="{{ $reg->name or old('name') }}">
            </div>
        </div>

        <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Salvar</button>
            </div>
        </div>
    </form>

@endsection